-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mersenne31]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace mersenne31

/- [core::num::{u32}::overflowing_sub]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2868:8-2868:69
   Name pattern: [core::num::{u32}::overflowing_sub] -/
@[rust_fun "core::num::{u32}::overflowing_sub"]
axiom core.num.U32.overflowing_sub
  : Std.U32 → Std.U32 → Result (Std.U32 × Bool)

/- Trait declaration: [core::ops::arith::Add]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 77:0-77:31
   Name pattern: [core::ops::arith::Add] -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/- Trait declaration: [core::ops::arith::Sub]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 190:0-190:31
   Name pattern: [core::ops::arith::Sub] -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/- Trait declaration: [core::ops::arith::Mul]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 324:0-324:31
   Name pattern: [core::ops::arith::Mul] -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/- Trait declaration: [core::ops::arith::Neg]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 692:0-692:19
   Name pattern: [core::ops::arith::Neg] -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/- Trait declaration: [core::ops::arith::AddAssign]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 769:0-769:37
   Name pattern: [core::ops::arith::AddAssign] -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/- Trait declaration: [core::ops::arith::SubAssign]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 840:0-840:37
   Name pattern: [core::ops::arith::SubAssign] -/
@[rust_trait "core::ops::arith::SubAssign"]
structure core.ops.arith.SubAssign (Self : Type) (Rhs : Type) where
  sub_assign : Self → Rhs → Result Self

/- Trait declaration: [core::ops::arith::MulAssign]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 902:0-902:37
   Name pattern: [core::ops::arith::MulAssign] -/
@[rust_trait "core::ops::arith::MulAssign"]
structure core.ops.arith.MulAssign (Self : Type) (Rhs : Type) where
  mul_assign : Self → Rhs → Result Self

/- Trait declaration: [mersenne31::field::PrimeField64]
   Source: 'src/field.rs', lines 9:0-19:1 -/
structure field.PrimeField64 (Self : Type) where
  ORDER_U64 : Result Std.U64
  as_canonical_u64 : Self → Result Std.U64
  to_unique_u64 : Self → Result Std.U64

/- [mersenne31::field::PrimeField64::to_unique_u64]:
   Source: 'src/field.rs', lines 15:4-18:5 -/
def field.PrimeField64.to_unique_u64.default
  {Self : Type} (PrimeField64Inst : field.PrimeField64 Self) (self : Self) :
  Result Std.U64
  := do
  PrimeField64Inst.as_canonical_u64 self

/- Trait declaration: [mersenne31::field::PrimeField32]
   Source: 'src/field.rs', lines 24:0-34:1 -/
structure field.PrimeField32 (Self : Type) where
  ORDER_U32 : Result Std.U32
  as_canonical_u32 : Self → Result Std.U32
  to_unique_u32 : Self → Result Std.U32

/- [mersenne31::field::PrimeField32::to_unique_u32]:
   Source: 'src/field.rs', lines 30:4-33:5 -/
def field.PrimeField32.to_unique_u32.default
  {Self : Type} (PrimeField32Inst : field.PrimeField32 Self) (self : Self) :
  Result Std.U32
  := do
  PrimeField32Inst.as_canonical_u32 self

/- Trait declaration: [mersenne31::unimplemented::Iterator]
   Source: 'src/unimplemented.rs', lines 2:0-5:1 -/
structure unimplemented.Iterator (Self : Type) (Self_Item : Type) where

/- Trait declaration: [mersenne31::unimplemented::Product]
   Source: 'src/unimplemented.rs', lines 15:0-19:1 -/
structure unimplemented.Product (Self : Type) (A : Type) where
  product : forall {I : Type} (IteratorInst : unimplemented.Iterator I A), I
    → Result Self

/- Trait declaration: [mersenne31::unimplemented::Sum]
   Source: 'src/unimplemented.rs', lines 8:0-12:1 -/
structure unimplemented.Sum (Self : Type) (A : Type) where
  sum : forall {I : Type} (IteratorInst : unimplemented.Iterator I A), I →
    Result Self

/- Trait declaration: [mersenne31::field::PrimeCharacteristicRing]
   Source: 'src/field.rs', lines 37:0-86:1 -/
structure field.PrimeCharacteristicRing (Self : Type) (Self_PrimeSubfield :
  Type) (Self_Clause4_Output : Type) (Self_Clause6_Output : Type)
  (Self_Clause7_Output : Type) where
  ZERO : Result Self
  ONE : Result Self
  TWO : Result Self
  NEG_ONE : Result Self
  coredefaultDefaultInst : core.default.Default Self
  corecloneCloneInst : core.clone.Clone Self
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  coreopsarithAddAssignInst : core.ops.arith.AddAssign Self Self
  coreopsarithSubInst : core.ops.arith.Sub Self Self Self_Clause4_Output
  coreopsarithSubAssignInst : core.ops.arith.SubAssign Self Self
  coreopsarithNegInst : core.ops.arith.Neg Self Self_Clause6_Output
  coreopsarithMulInst : core.ops.arith.Mul Self Self Self_Clause7_Output
  coreopsarithMulAssignInst : core.ops.arith.MulAssign Self Self
  unimplementedSumInst : unimplemented.Sum Self Self
  unimplementedProductInst : unimplemented.Product Self Self
  from_prime_subfield : Self_PrimeSubfield → Result Self
  from_bool : Bool → Result Self
  double : Self → Result Self
  halve : Self → Result Self

/- [mersenne31::field::PrimeCharacteristicRing::from_bool]:
   Source: 'src/field.rs', lines 63:4-66:5 -/
def field.PrimeCharacteristicRing.from_bool.default
  {Self : Type} {Clause0_PrimeSubfield : Type} {Clause0_Clause4_Output : Type}
  {Clause0_Clause6_Output : Type} {Clause0_Clause7_Output : Type}
  (PrimeCharacteristicRingInst : field.PrimeCharacteristicRing Self
  Clause0_PrimeSubfield Clause0_Clause4_Output Clause0_Clause6_Output
  Clause0_Clause7_Output) (b : Bool) :
  Result Self
  := do
  if b
  then PrimeCharacteristicRingInst.ONE
  else PrimeCharacteristicRingInst.ZERO

/- [mersenne31::field::PrimeCharacteristicRing::double]:
   Source: 'src/field.rs', lines 69:4-71:5 -/
def field.PrimeCharacteristicRing.double.default
  {Self : Type} {Clause0_PrimeSubfield : Type} {Clause0_Clause4_Output : Type}
  {Clause0_Clause6_Output : Type} {Clause0_Clause7_Output : Type}
  (PrimeCharacteristicRingInst : field.PrimeCharacteristicRing Self
  Clause0_PrimeSubfield Clause0_Clause4_Output Clause0_Clause6_Output
  Clause0_Clause7_Output) (self : Self) :
  Result Self
  := do
  let t ← PrimeCharacteristicRingInst.corecloneCloneInst.clone self
  PrimeCharacteristicRingInst.coreopsarithAddInst.add t t

/- [mersenne31::field::PrimeCharacteristicRing::halve]:
   Source: 'src/field.rs', lines 77:4-84:5 -/
def field.PrimeCharacteristicRing.halve.default
  {Self : Type} {Clause0_PrimeSubfield : Type} {Clause0_Clause4_Output : Type}
  {Clause0_Clause6_Output : Type} {Clause0_Clause7_Output : Type}
  (PrimeCharacteristicRingInst : field.PrimeCharacteristicRing Self
  Clause0_PrimeSubfield Clause0_Clause4_Output Clause0_Clause6_Output
  Clause0_Clause7_Output) (self : Self) :
  Result Self
  := do
  PrimeCharacteristicRingInst.corecloneCloneInst.clone self

/- [mersenne31::mersenne31::P]
   Source: 'src/mersenne31.rs', lines 6:0-6:29 -/
@[global_simps, irreducible]
def mersenne31.P : Result Std.U32 := do let i ← 1#u32 <<< 31#i32
                                        i - 1#u32

/- [mersenne31::mersenne31::P64]
   Source: 'src/mersenne31.rs', lines 8:0-8:31 -/
@[global_simps, irreducible]
def mersenne31.P64 : Result Std.U64 := do let i ← 1#u64 <<< 31#i32
                                          i - 1#u64

/- [mersenne31::mersenne31::Mersenne31]
   Source: 'src/mersenne31.rs', lines 14:0-17:1 -/
structure mersenne31.Mersenne31 where
  value : Std.U32

/- [mersenne31::mersenne31::{core::clone::Clone for mersenne31::mersenne31::Mersenne31}::clone]:
   Source: 'src/mersenne31.rs', lines 11:15-11:20 -/
def mersenne31.Mersenne31.Insts.CoreCloneClone.clone
  (self : mersenne31.Mersenne31) : Result mersenne31.Mersenne31 := do
  ok self

/- Trait implementation: [mersenne31::mersenne31::{core::clone::Clone for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 11:15-11:20 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreCloneClone : core.clone.Clone
  mersenne31.Mersenne31 := {
  clone := mersenne31.Mersenne31.Insts.CoreCloneClone.clone
}

/- Trait implementation: [mersenne31::mersenne31::{core::marker::Copy for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 11:9-11:13 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreMarkerCopy : core.marker.Copy
  mersenne31.Mersenne31 := {
  cloneInst := mersenne31.Mersenne31.Insts.CoreCloneClone
}

/- [mersenne31::mersenne31::{core::default::Default for mersenne31::mersenne31::Mersenne31}::default]:
   Source: 'src/mersenne31.rs', lines 11:22-11:29 -/
def mersenne31.Mersenne31.Insts.CoreDefaultDefault.default
  : Result mersenne31.Mersenne31 := do
  ok { value := (core.default.DefaultU32.default) }

/- Trait implementation: [mersenne31::mersenne31::{core::default::Default for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 11:22-11:29 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreDefaultDefault : core.default.Default
  mersenne31.Mersenne31 := {
  default := mersenne31.Mersenne31.Insts.CoreDefaultDefault.default
}

/- [mersenne31::mersenne31::{mersenne31::mersenne31::Mersenne31}::new]:
   Source: 'src/mersenne31.rs', lines 24:4-26:5 -/
def mersenne31.Mersenne31.new
  (value : Std.U32) : Result mersenne31.Mersenne31 := do
  let i ← mersenne31.P
  let i1 ← value % i
  ok { value := i1 }

/- [mersenne31::mersenne31::{mersenne31::mersenne31::Mersenne31}::new_reduced]:
   Source: 'src/mersenne31.rs', lines 33:4-37:5 -/
def mersenne31.Mersenne31.new_reduced
  (value : Std.U32) : Result mersenne31.Mersenne31 := do
  let i ← value >>> 31#i32
  massert (i = 0#u32)
  ok { value }

/- [mersenne31::mersenne31::{mersenne31::mersenne31::Mersenne31}::new_checked]:
   Source: 'src/mersenne31.rs', lines 43:4-49:5 -/
def mersenne31.Mersenne31.new_checked
  (value : Std.U32) : Result (Option mersenne31.Mersenne31) := do
  let i ← value >>> 31#i32
  if i = 0#u32
  then ok (some { value })
  else ok none

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::ZERO]
   Source: 'src/mersenne31.rs', lines 69:4-69:41 -/
@[global_simps, irreducible]
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.ZERO
  : mersenne31.Mersenne31 :=
  { value := 0#u32 }

/- [mersenne31::mersenne31::{mersenne31::mersenne31::Mersenne31}::new_array]: loop 0:
   Source: 'src/mersenne31.rs', lines 58:8-61:9 -/
def mersenne31.Mersenne31.new_array_loop
  {N : Std.Usize} (input : Array Std.U32 N)
  (output : Array mersenne31.Mersenne31 N) (i : Std.Usize) :
  Result (Array mersenne31.Mersenne31 N)
  := do
  loop
    (fun (output1, i1) =>
      if i1 < N
      then
        do
        let i2 ← Array.index_usize input i1
        let a ← Array.update output1 i1 ()
        let i3 ← mersenne31.P
        let _ ← i2 % i3
        let i4 ← i1 + 1#usize
        ok (cont (a, i4))
      else ok (done output1))
    (output, i)

/- [mersenne31::mersenne31::{mersenne31::mersenne31::Mersenne31}::new_array]:
   Source: 'src/mersenne31.rs', lines 55:4-63:5 -/
def mersenne31.Mersenne31.new_array
  {N : Std.Usize} (input : Array Std.U32 N) :
  Result (Array mersenne31.Mersenne31 N)
  := do
  let output :=
    Array.repeat N
      mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.ZERO
  mersenne31.Mersenne31.new_array_loop input output 0#usize

/- [mersenne31::mersenne31::{mersenne31::unimplemented::Product<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::product]:
   Source: 'src/mersenne31.rs', lines 219:4-221:5 -/
def
  mersenne31.Mersenne31.Insts.Mersenne31UnimplementedProductMersenne31.product
  {I : Type} (unimplementedIteratorIMersenne31Inst : unimplemented.Iterator I
  mersenne31.Mersenne31) (iter : I) :
  Result mersenne31.Mersenne31
  := do
  mersenne31.Mersenne31.new 0#u32

/- Trait implementation: [mersenne31::mersenne31::{mersenne31::unimplemented::Product<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 218:0-222:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.Mersenne31UnimplementedProductMersenne31 :
  unimplemented.Product mersenne31.Mersenne31 mersenne31.Mersenne31 := {
  product := fun {I : Type} (unimplementedIteratorPMersenne31Inst :
    unimplemented.Iterator I mersenne31.Mersenne31) =>
    mersenne31.Mersenne31.Insts.Mersenne31UnimplementedProductMersenne31.product
    unimplementedIteratorPMersenne31Inst
}

/- [mersenne31::mersenne31::{mersenne31::unimplemented::Sum<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::sum]:
   Source: 'src/mersenne31.rs', lines 212:4-214:5 -/
def mersenne31.Mersenne31.Insts.Mersenne31UnimplementedSumMersenne31.sum
  {I : Type} (unimplementedIteratorIMersenne31Inst : unimplemented.Iterator I
  mersenne31.Mersenne31) (iter : I) :
  Result mersenne31.Mersenne31
  := do
  mersenne31.Mersenne31.new 0#u32

/- Trait implementation: [mersenne31::mersenne31::{mersenne31::unimplemented::Sum<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 200:0-215:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.Mersenne31UnimplementedSumMersenne31 :
  unimplemented.Sum mersenne31.Mersenne31 mersenne31.Mersenne31 := {
  sum := fun {I : Type} (unimplementedIteratorPMersenne31Inst :
    unimplemented.Iterator I mersenne31.Mersenne31) =>
    mersenne31.Mersenne31.Insts.Mersenne31UnimplementedSumMersenne31.sum
    unimplementedIteratorPMersenne31Inst
}

/- [mersenne31::mersenne31::{mersenne31::field::PrimeField32 for mersenne31::mersenne31::Mersenne31}::ORDER_U32]
   Source: 'src/mersenne31.rs', lines 104:4-104:29 -/
@[global_simps, irreducible]
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.ORDER_U32
  : Std.U32 := do
  let i ← mersenne31.P
  i

/- [mersenne31::mersenne31::{core::ops::arith::Add<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::add]:
   Source: 'src/mersenne31.rs', lines 120:4-135:5 -/
def mersenne31.Mersenne31.Insts.CoreOpsArithAddMersenne31Mersenne31.add
  (self : mersenne31.Mersenne31) (rhs : mersenne31.Mersenne31) :
  Result mersenne31.Mersenne31
  := do
  let i ← lift (UScalar.hcast .I32 self.value)
  let i1 ← lift (UScalar.hcast .I32 rhs.value)
  let (sum_i32, over) ← lift (core.num.I32.overflowing_add i i1)
  let sum_u32 ← lift (IScalar.hcast .U32 sum_i32)
  let sum_corr ←
    lift (core.num.U32.wrapping_sub sum_u32
      mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.ORDER_U32)
  let sum_corr1 ← if over
                    then ok sum_corr
                    else ok sum_u32
  mersenne31.Mersenne31.new_reduced sum_corr1

/- [mersenne31::mersenne31::from_u62]:
   Source: 'src/mersenne31.rs', lines 224:0-230:1 -/
def mersenne31.from_u62 (input : Std.U64) : Result mersenne31.Mersenne31 := do
  let i ← 1#u64 <<< 62#i32
  massert (input < i)
  let i1 ← 1#u64 <<< 31#i32
  let i2 ← i1 - 1#u64
  let i3 ← lift (input &&& i2)
  let input_lo ← lift (UScalar.cast .U32 i3)
  let i4 ← input >>> 31#i32
  let input_high ← lift (UScalar.cast .U32 i4)
  let m ← mersenne31.Mersenne31.new_reduced input_lo
  let m1 ← mersenne31.Mersenne31.new_reduced input_high
  mersenne31.Mersenne31.Insts.CoreOpsArithAddMersenne31Mersenne31.add m m1

/- [mersenne31::mersenne31::{core::ops::arith::Mul<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::mul]:
   Source: 'src/mersenne31.rs', lines 169:4-172:5 -/
def mersenne31.Mersenne31.Insts.CoreOpsArithMulMersenne31Mersenne31.mul
  (self : mersenne31.Mersenne31) (rhs : mersenne31.Mersenne31) :
  Result mersenne31.Mersenne31
  := do
  let i ← lift (core.convert.num.FromU64U32.from self.value)
  let i1 ← lift (core.convert.num.FromU64U32.from rhs.value)
  let prod ← i * i1
  mersenne31.from_u62 prod

/- [mersenne31::mersenne31::{core::ops::arith::MulAssign<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::mul_assign]:
   Source: 'src/mersenne31.rs', lines 194:4-196:5 -/
def mersenne31.Mersenne31.Insts.CoreOpsArithMulAssignMersenne31.mul_assign
  (self : mersenne31.Mersenne31) (rhs : mersenne31.Mersenne31) :
  Result mersenne31.Mersenne31
  := do
  let m ←
    core.convert.IntoFrom.into (core.convert.FromSame mersenne31.Mersenne31)
      rhs
  mersenne31.Mersenne31.Insts.CoreOpsArithMulMersenne31Mersenne31.mul self m

/- Trait implementation: [mersenne31::mersenne31::{core::ops::arith::MulAssign<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 193:0-197:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreOpsArithMulAssignMersenne31 :
  core.ops.arith.MulAssign mersenne31.Mersenne31 mersenne31.Mersenne31 := {
  mul_assign :=
    mersenne31.Mersenne31.Insts.CoreOpsArithMulAssignMersenne31.mul_assign
}

/- [mersenne31::mersenne31::{core::ops::arith::Sub<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::sub]:
   Source: 'src/mersenne31.rs', lines 142:4-151:5 -/
def mersenne31.Mersenne31.Insts.CoreOpsArithSubMersenne31Mersenne31.sub
  (self : mersenne31.Mersenne31) (rhs : mersenne31.Mersenne31) :
  Result mersenne31.Mersenne31
  := do
  let (sub, over) ← core.num.U32.overflowing_sub self.value rhs.value
  let i ← lift (UScalar.cast_fromBool .U32 over)
  let sub1 ← sub - i
  let i1 ←
    lift (sub1 &&&
      mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.ORDER_U32)
  mersenne31.Mersenne31.new_reduced i1

/- [mersenne31::mersenne31::{core::ops::arith::SubAssign<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::sub_assign]:
   Source: 'src/mersenne31.rs', lines 186:4-188:5 -/
def mersenne31.Mersenne31.Insts.CoreOpsArithSubAssignMersenne31.sub_assign
  (self : mersenne31.Mersenne31) (rhs : mersenne31.Mersenne31) :
  Result mersenne31.Mersenne31
  := do
  let m ←
    core.convert.IntoFrom.into (core.convert.FromSame mersenne31.Mersenne31)
      rhs
  mersenne31.Mersenne31.Insts.CoreOpsArithSubMersenne31Mersenne31.sub self m

/- Trait implementation: [mersenne31::mersenne31::{core::ops::arith::SubAssign<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 185:0-189:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreOpsArithSubAssignMersenne31 :
  core.ops.arith.SubAssign mersenne31.Mersenne31 mersenne31.Mersenne31 := {
  sub_assign :=
    mersenne31.Mersenne31.Insts.CoreOpsArithSubAssignMersenne31.sub_assign
}

/- [mersenne31::mersenne31::{core::ops::arith::AddAssign<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::add_assign]:
   Source: 'src/mersenne31.rs', lines 178:4-180:5 -/
def mersenne31.Mersenne31.Insts.CoreOpsArithAddAssignMersenne31.add_assign
  (self : mersenne31.Mersenne31) (rhs : mersenne31.Mersenne31) :
  Result mersenne31.Mersenne31
  := do
  let m ←
    core.convert.IntoFrom.into (core.convert.FromSame mersenne31.Mersenne31)
      rhs
  mersenne31.Mersenne31.Insts.CoreOpsArithAddMersenne31Mersenne31.add self m

/- Trait implementation: [mersenne31::mersenne31::{core::ops::arith::AddAssign<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 177:0-181:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreOpsArithAddAssignMersenne31 :
  core.ops.arith.AddAssign mersenne31.Mersenne31 mersenne31.Mersenne31 := {
  add_assign :=
    mersenne31.Mersenne31.Insts.CoreOpsArithAddAssignMersenne31.add_assign
}

/- Trait implementation: [mersenne31::mersenne31::{core::ops::arith::Mul<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 164:0-173:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreOpsArithMulMersenne31Mersenne31 :
  core.ops.arith.Mul mersenne31.Mersenne31 mersenne31.Mersenne31
  mersenne31.Mersenne31 := {
  mul := mersenne31.Mersenne31.Insts.CoreOpsArithMulMersenne31Mersenne31.mul
}

/- [mersenne31::mersenne31::{core::ops::arith::Neg<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::neg]:
   Source: 'src/mersenne31.rs', lines 158:4-161:5 -/
def mersenne31.Mersenne31.Insts.CoreOpsArithNegMersenne31.neg
  (self : mersenne31.Mersenne31) : Result mersenne31.Mersenne31 := do
  let i ←
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.ORDER_U32 -
      self.value
  mersenne31.Mersenne31.new_reduced i

/- Trait implementation: [mersenne31::mersenne31::{core::ops::arith::Neg<mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 154:0-162:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreOpsArithNegMersenne31 : core.ops.arith.Neg
  mersenne31.Mersenne31 mersenne31.Mersenne31 := {
  neg := mersenne31.Mersenne31.Insts.CoreOpsArithNegMersenne31.neg
}

/- Trait implementation: [mersenne31::mersenne31::{core::ops::arith::Sub<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 138:0-152:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreOpsArithSubMersenne31Mersenne31 :
  core.ops.arith.Sub mersenne31.Mersenne31 mersenne31.Mersenne31
  mersenne31.Mersenne31 := {
  sub := mersenne31.Mersenne31.Insts.CoreOpsArithSubMersenne31Mersenne31.sub
}

/- Trait implementation: [mersenne31::mersenne31::{core::ops::arith::Add<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 116:0-136:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.CoreOpsArithAddMersenne31Mersenne31 :
  core.ops.arith.Add mersenne31.Mersenne31 mersenne31.Mersenne31
  mersenne31.Mersenne31 := {
  add := mersenne31.Mersenne31.Insts.CoreOpsArithAddMersenne31Mersenne31.add
}

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::from_bool]:
   Source: 'src/mersenne31.rs', lines 82:4-84:5 -/
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.from_bool
  (b : Bool) : Result mersenne31.Mersenne31 := do
  let i ← lift (UScalar.cast_fromBool .U32 b)
  mersenne31.Mersenne31.new_reduced i

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::from_prime_subfield]:
   Source: 'src/mersenne31.rs', lines 77:4-79:5 -/
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.from_prime_subfield
  (f : mersenne31.Mersenne31) : Result mersenne31.Mersenne31 := do
  ok f

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::NEG_ONE]
   Source: 'src/mersenne31.rs', lines 72:4-74:6 -/
@[global_simps, irreducible]
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.NEG_ONE
  : Result mersenne31.Mersenne31 := do
  let i ←
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.ORDER_U32 - 1#u32
  ok { value := i }

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::TWO]
   Source: 'src/mersenne31.rs', lines 71:4-71:40 -/
@[global_simps, irreducible]
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.TWO
  : mersenne31.Mersenne31 :=
  { value := 2#u32 }

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::ONE]
   Source: 'src/mersenne31.rs', lines 70:4-70:40 -/
@[global_simps, irreducible]
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.ONE
  : mersenne31.Mersenne31 :=
  { value := 1#u32 }

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::halve]:
   Source: 'src/mersenne31.rs', lines 66:0-86:1 -/
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.halve
  (self : mersenne31.Mersenne31) : Result mersenne31.Mersenne31 := do
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.corecloneCloneInst.clone
    self

/- [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}::double]:
   Source: 'src/mersenne31.rs', lines 66:0-86:1 -/
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.double
  (self : mersenne31.Mersenne31) : Result mersenne31.Mersenne31 := do
  let m ←
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.corecloneCloneInst.clone
      self
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.coreopsarithAddInst.add
    m m

/- Trait implementation: [mersenne31::mersenne31::{mersenne31::field::PrimeCharacteristicRing<mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31, mersenne31::mersenne31::Mersenne31> for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 66:0-86:1 -/
@[reducible]
def
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31
  : field.PrimeCharacteristicRing mersenne31.Mersenne31 mersenne31.Mersenne31
  mersenne31.Mersenne31 mersenne31.Mersenne31 mersenne31.Mersenne31 := {
  ZERO := ok
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.ZERO
  ONE := ok
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.ONE
  TWO := ok
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.TWO
  NEG_ONE :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.NEG_ONE
  coredefaultDefaultInst := mersenne31.Mersenne31.Insts.CoreDefaultDefault
  corecloneCloneInst := mersenne31.Mersenne31.Insts.CoreCloneClone
  coreopsarithAddInst :=
    mersenne31.Mersenne31.Insts.CoreOpsArithAddMersenne31Mersenne31
  coreopsarithAddAssignInst :=
    mersenne31.Mersenne31.Insts.CoreOpsArithAddAssignMersenne31
  coreopsarithSubInst :=
    mersenne31.Mersenne31.Insts.CoreOpsArithSubMersenne31Mersenne31
  coreopsarithSubAssignInst :=
    mersenne31.Mersenne31.Insts.CoreOpsArithSubAssignMersenne31
  coreopsarithNegInst := mersenne31.Mersenne31.Insts.CoreOpsArithNegMersenne31
  coreopsarithMulInst :=
    mersenne31.Mersenne31.Insts.CoreOpsArithMulMersenne31Mersenne31
  coreopsarithMulAssignInst :=
    mersenne31.Mersenne31.Insts.CoreOpsArithMulAssignMersenne31
  unimplementedSumInst :=
    mersenne31.Mersenne31.Insts.Mersenne31UnimplementedSumMersenne31
  unimplementedProductInst :=
    mersenne31.Mersenne31.Insts.Mersenne31UnimplementedProductMersenne31
  from_prime_subfield :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.from_prime_subfield
  from_bool :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.from_bool
  double :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.double
  halve :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeCharacteristicRingMersenne31Mersenne31Mersenne31Mersenne31.halve
}

/- [mersenne31::mersenne31::{mersenne31::field::PrimeField32 for mersenne31::mersenne31::Mersenne31}::as_canonical_u32]:
   Source: 'src/mersenne31.rs', lines 105:4-113:5 -/
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.as_canonical_u32
  (self : mersenne31.Mersenne31) : Result Std.U32 := do
  if self.value =
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.ORDER_U32
  then ok 0#u32
  else ok self.value

/- [mersenne31::mersenne31::{mersenne31::field::PrimeField64 for mersenne31::mersenne31::Mersenne31}::as_canonical_u64]:
   Source: 'src/mersenne31.rs', lines 97:4-99:5 -/
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64.as_canonical_u64
  (self : mersenne31.Mersenne31) : Result Std.U64 := do
  let i ←
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.as_canonical_u32
      self
  core.convert.IntoFrom.into core.convert.FromU64U32 i

/- [mersenne31::mersenne31::{mersenne31::field::PrimeField64 for mersenne31::mersenne31::Mersenne31}::ORDER_U64]
   Source: 'src/mersenne31.rs', lines 95:4-95:32 -/
@[global_simps, irreducible]
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64.ORDER_U64
  : Std.U64 := do
  let i ← mersenne31.P64
  i

/- [mersenne31::mersenne31::{mersenne31::field::PrimeField64 for mersenne31::mersenne31::Mersenne31}::to_unique_u64]:
   Source: 'src/mersenne31.rs', lines 93:0-100:1 -/
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64.to_unique_u64
  (self : mersenne31.Mersenne31) : Result Std.U64 := do
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64.as_canonical_u64 self

/- Trait implementation: [mersenne31::mersenne31::{mersenne31::field::PrimeField64 for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 93:0-100:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64 :
  field.PrimeField64 mersenne31.Mersenne31 := {
  ORDER_U64 := ok
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64.ORDER_U64
  as_canonical_u64 :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64.as_canonical_u64
  to_unique_u64 :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField64.to_unique_u64
}

/- [mersenne31::mersenne31::{mersenne31::field::PrimeField32 for mersenne31::mersenne31::Mersenne31}::to_unique_u32]:
   Source: 'src/mersenne31.rs', lines 103:0-114:1 -/
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.to_unique_u32
  (self : mersenne31.Mersenne31) : Result Std.U32 := do
  mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.as_canonical_u32 self

/- Trait implementation: [mersenne31::mersenne31::{mersenne31::field::PrimeField32 for mersenne31::mersenne31::Mersenne31}]
   Source: 'src/mersenne31.rs', lines 103:0-114:1 -/
@[reducible]
def mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32 :
  field.PrimeField32 mersenne31.Mersenne31 := {
  ORDER_U32 := ok
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.ORDER_U32
  as_canonical_u32 :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.as_canonical_u32
  to_unique_u32 :=
    mersenne31.Mersenne31.Insts.Mersenne31FieldPrimeField32.to_unique_u32
}

end mersenne31
