-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [fold_step]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

set_option maxHeartbeats 1000000

namespace fold_step

end fold_step
