-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [fold_step]: function definitions
import Aeneas
import FoldStep.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace fold_step

/-- [fold_step::fold_step]:
    Source: 'src/lib.rs', lines 8:0-21:1 -/
def fold_step
  (lo : Std.U64) (hi : Std.U64) (beta : Std.U64) (x_inv : Std.U64)
  (two_inv : Std.U64) (p : Std.U64) :
  Result Std.U64
  := do
  let i ← lo + hi
  let sum ← i % p
  let i1 ← lo + p
  let i2 ← i1 - hi
  let diff ← i2 % p
  let i3 ← diff * x_inv
  let t ← i3 % p
  let i4 ← beta * t
  let bt ← i4 % p
  let i5 ← sum + bt
  let i6 ← i5 % p
  let i7 ← i6 * two_inv
  i7 % p

end fold_step
